services:
  nats:
    image: nats:latest
    command:
      - "--jetstream"
      - "--store_dir=/data"
      - "--http_port=8222"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats-data:/data
    restart: unless-stopped

#  bootstrap:
#    build:
#      context: .
#      target: bootstrap
#    depends_on:
#      - nats
#    volumes:
#      - ./config.docker.yaml:/app/config.yaml:ro
#    restart: on-failure

#  modbus-service:
#    build:
#      context: .
#      target: modbus-service
#    depends_on:
#      bootstrap:
#        condition: service_completed_successfully
#    volumes:
#      - ./config.docker.yaml:/app/config.yaml:ro
#    restart: unless-stopped

#  alert-service:
#    build:
#      context: .
#      target: alert-service
#    depends_on:
#      bootstrap:
#        condition: service_completed_successfully
#    volumes:
#      - ./config.docker.yaml:/app/config.yaml:ro
#    restart: unless-stopped

  designer:
    build:
      context: .
      target: designer
#    depends_on:
#      bootstrap:
#        condition: service_completed_successfully
    ports:
      - "8080:8080"
    volumes:
      - ./config.docker.yaml:/app/config.yaml:ro
    restart: unless-stopped
